# src/main/resources/application.yml
spring:
  application:
    name: network-monitoring-dashboard

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8080