global:
  resolve_timeout: 5m

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'inkzxd@gmail.com'
  smtp_auth_username: 'inkzxd@gmail.com'
  smtp_auth_password: 'resyzvyoepabbcfv'
  smtp_require_tls: true

route:
  receiver: spring-boot-email-webhook
  group_by:
    - alertname
    - device
    - host
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: spring-boot-email-webhook

    webhook_configs:
      - url: http://app:8080/api/alerts
        send_resolved: true
        http_config:
          basic_auth:
            username: admin
            password: change-me-in-production

    email_configs:
      - to: 'inkzxd@icloud.com'
        send_resolved: true